server:
  port: 7779
  address: 0.0.0.0

  # 数据库相关配置
spring:
  datasource:
    url: jdbc:mysql://175.178.90.196:3306/ISdata
    username: InnerScape
    password: Dbzlz2023@LYL0408_21:21
    driver-class-name: com.mysql.cj.jdbc.Driver
#  web:
#    resources:
#      static-locations: file:D:\appData\codeProject\photoResource\resource
      # /home/ubuntu/ranzhaoTest/resource
      # D:\appData\codeProject\photoResource\resource
      # /home/ubuntu/resource
